export { default as AdminDocs } from "./Docs";
export { default as Home } from "./Home";
export { default as LockerRoom } from "./LockerRoom";
export { default as Login } from "./Login";
export { default as Playgrounds } from "./Playgrounds";
export { default as Posts } from "./Posts";
export { default as Profile } from "./Profile";
export { default as Register } from "./Register";
export { default as Sites } from "./Sites";
// export { default as Site } from "./components/Site";
// export * from "./BitCoin";
